// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIKYz-BuBHTsMF2WHLzIBtd3_SSX5eqtI',
    appId: '1:222264403034:web:e443f94cfb5ffef0726463',
    messagingSenderId: '222264403034',
    projectId: 'payroll-app-6133c',
    authDomain: 'payroll-app-6133c.firebaseapp.com',
    storageBucket: 'payroll-app-6133c.appspot.com',
    measurementId: 'G-YQMPMRRGL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6WQMT_IS-HIsMAod-4mSpTmFqixec-tQ',
    appId: '1:222264403034:android:4c2d7a1ff42fc76f726463',
    messagingSenderId: '222264403034',
    projectId: 'payroll-app-6133c',
    storageBucket: 'payroll-app-6133c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsDCXhdVuM-GYAtYCfUNAXX6vgHkvaN9g',
    appId: '1:222264403034:ios:59c93f7dd0609037726463',
    messagingSenderId: '222264403034',
    projectId: 'payroll-app-6133c',
    storageBucket: 'payroll-app-6133c.appspot.com',
    iosBundleId: 'com.example.payrollApp',
  );

}